=== dalzilio/dalzilio.github.io/generators/biblio.dtd
<!ELEMENT bibliography (inproceedings | techreport |
                        phdthesis | article | unpublished)*>
<!ATTLIST bibliography author CDATA #REQUIRED>
<!ELEMENT inproceedings (authors | title | booktitle | year | tags |
                      volume | pages | series | publisher | note | 
                      month | url | abstract | editors | project |
                      copyright | referto | arxiv | hal | doi | referby)*>
<!ATTLIST inproceedings key ID #REQUIRED>
<!ELEMENT techreport (authors | title | year | tags |
                      month | url | abstract | note |
                      institution | number |  project |
                      copyright | referto | referby | hal | arxiv)*>
<!ATTLIST techreport key ID #REQUIRED>
<!ELEMENT phdthesis (authors | title | school | year | tags |
                      month | url | abstract | note |
                      institution | number |  project |
                      copyright | referto | referby)*>
<!ATTLIST phdthesis key ID #REQUIRED>
<!ELEMENT article (authors | title | year | journal | tags |
                   volume | pages | publisher | note | number |
                   month | url | abstract | project |
                   copyright | referto | referby | hal | arxiv | doi)*>
<!ATTLIST article key ID #REQUIRED>
<!ELEMENT unpublished (authors | title | booktitle | year | tags |
                      volume | pages | series | publisher |  project |
                      month | url | abstract | editors | note |
                      copyright | referto | referby | arxiv | hal)*>
<!ATTLIST unpublished key ID #REQUIRED>
<!ELEMENT authors (author)*>
<!ELEMENT editors (author)*>
<!ELEMENT author (name, forename)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT forename (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT note (#PCDATA)>
<!ELEMENT journal (#PCDATA)>
<!ELEMENT institution (#PCDATA)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT school (#PCDATA)>
<!ELEMENT booktitle (short, long)>
<!ELEMENT short  (#PCDATA)>
<!ELEMENT long   (#PCDATA)>
<!ELEMENT year   (#PCDATA)>
<!ELEMENT volume (#PCDATA)>
<!ELEMENT month  (#PCDATA)>
<!ELEMENT series  (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT project (#PCDATA)>
<!ELEMENT tags (#PCDATA)>
<!ELEMENT arxiv (#PCDATA)>
<!ELEMENT hal (#PCDATA)>
<!ATTLIST hal
		  type CDATA #IMPLIED>
<!ELEMENT doi (#PCDATA)>
<!ELEMENT pages EMPTY>
<!ATTLIST pages 
          bgn NMTOKEN #REQUIRED
          end NMTOKEN #REQUIRED>
<!ELEMENT url EMPTY>
<!ATTLIST url 
          type (ps | pdf | web | lit) #REQUIRED
          href CDATA #REQUIRED>
<!ELEMENT copyright EMPTY>
<!ATTLIST copyright
          organization NMTOKEN #REQUIRED>
<!ELEMENT referto ANY>
<!ATTLIST referto
          key IDREF #REQUIRED>
<!ELEMENT referby EMPTY>
<!ATTLIST referby
          key IDREF #REQUIRED>
<!ELEMENT abstract (p)*>
<!ELEMENT p (#PCDATA | em)*>
<!ELEMENT em (#PCDATA)>

=== dalzilio/dalzilio.github.io/generators/DalzilioS.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE bibliography SYSTEM "biblio.dtd" [
  <!ENTITY LNCS "Lecture Notes in Computer Science">
  <!ENTITY SV "Springer-Verlag">
  <!ENTITY IEEE "IEEE Computer Society">
  <!ENTITY dalzilio "<name>Dal Zilio</name><forename>Silvano</forename>">
  <!ENTITY amadio "<name>Amadio</name><forename>Roberto M.</forename>">
  <!ENTITY acciai "<name>Acciai</name><forename>Lucia</forename>">
  <!ENTITY abid "<name>Abid</name><forename>Nouha</forename>">
  <!ENTITY didier "<name>Le Botlan</name><forename>Didier</forename>">
  <!ENTITY lugiez "<name>Lugiez</name><forename>Denis</forename>">
  <!ENTITY gordon "<name>Gordon</name><forename>Andrew D.</forename>">
  <!ENTITY gascon "<name>Gascon</name><forename>R&#x00E9;gis</forename>">
  <!ENTITY boreale "<name>Boreale</name> <forename>Michele</forename>">
  <!ENTITY francois "<name>Vernadat</name> <forename>Fran&#x00E7;ois</forename>">
  <!ENTITY bernard "<name>Berthomieu</name> <forename>Bernard</forename>">
  <!ENTITY mamoun "<name>Filali</name> <forename>Mamoun</forename>">
  <!ENTITY nawal "<name>Guermouche</name> <forename>Nawal</forename>">
  <!ENTITY bodeveix "<name>Bodeveix</name> <forename>Jean-Paul</forename>">
  <!ENTITY chaudet "<name>Chaudet</name> <forename>Christelle</forename>">
  <!ENTITY rodrigo "<name>Tacla Saad</name> <forename>Rodrigo</forename>">
  <!ENTITY dissaux "<name>Dissaux</name> <forename>Pierre</forename>">
  <!ENTITY gaufillet "<name>Gaufillet</name> <forename>Pierre</forename>">
  <!ENTITY heim "<name>Heim</name> <forename>S&#x00E9;bastien</forename>">
  <!ENTITY pantel "<name>Pantel</name> <forename>Marc</forename>">
  <!ENTITY lukasz "<name>Fronc</name> <forename>Lukasz</forename>">
  <!ENTITY bourdil "<name>Bourdil</name> <forename>Pierre-Alain</forename>">
  <!ENTITY avellaneda "<name>Avellaneda</name> <forename>Florent</forename>">
  <!ENTITY raclet "<name>Raclet</name> <forename>Jean-Baptiste</forename>">
  <!ENTITY jenn "<name>Jenn</name> <forename>Éric</forename>">
  <!ENTITY hladik "<name>Hladik</name> <forename>Pierre-Emmanuel</forename>">
  <!ENTITY foughali "<name>Foughali</name> <forename>Mohammed</forename>">
  <!ENTITY namat "<name>Amat</name> <forename>Nicolas</forename>">
  <!ENTITY hujsa "<name>Hujsa</name>  <forename>Thomas</forename>">
  <!ENTITY mdash "&#8212;">
]>

<bibliography author="DalzilioS">
  <inproceedings key="learnbs">
    <authors>
      <author>&dalzilio;</author>
      <author>
        <name>Bernard</name>
        <forename>Thierry M.</forename>
      </author>
    </authors>
    <title>Learning Binary Shapes as Compression and its Cellular Implementation</title>
    <booktitle>
      <short>ACCV'95</short>
      <long>2nd Asian Conference on Computer Vision</long>
    </booktitle>
    <year>1995</year>
    <volume>II</volume>
    <pages bgn="616" end="620" />
    <month>12</month>
    <url type="pdf" href="Papers/accv95.pdf" />
    <abstract>
      <p>We present a methodology to learn how to recognize binary shapes, based on the principle
        that recognition may be understood as a process of information compression. Our approach,
        directed towards adaptive target tracking applications, is intended to be well suited to
        fine-grained parallel architectures, such as cellular automata machines that can be
        integrated in artificial retinas. This methodology, fruitfully explained within the frame of
        mathematical morphology, is then particularized in the perspective of its actual
        implementation.</p>
    </abstract>
  </inproceedings>

  <techreport key="rr3244">
    <authors>
      <author>&dalzilio;</author>
    </authors>
    <title>Implicit Polymorphic Type System for the Blue Calculus</title>
    <institution>INRIA</institution>
    <year>1997</year>
    <number>3244</number>
    <month>9</month>
    <url type="pdf" href="Papers/RR-3244.pdf" />
    <hal type="INRIA">00073445</hal>
    <abstract>
      <p>The Blue Calculus is a direct extension of both the lambda and the pi calculi. In a
        preliminary work from Gérard Boudol, a simple type system was given that incorporates
        Curry's type inference for the lambda-calculus. In the present paper we study an implicit
        polymorphic type system, adapted from the ML typing discipline. Our typing system enjoys
        subject reduction and principal type properties and we give results on the complexity for
        the type inference problem. These are interesting results for the blue calculus as a
        programming notation for higher-order concurrency.</p>
    </abstract>
    <copyright organization="INRIA" />
    <tags>Semantics, Concurrency</tags>
  </techreport>

  <inproceedings key="bouncingobj">
    <authors>
      <author>&dalzilio;</author>
    </authors>
    <title>Quiet and Bouncing Objects: Two Migration Abstractions in a Simple Distributed Blue
      Calculus</title>
    <booktitle>
      <short>SOAP'98</short>
      <long>1st International Workshop on Semantics of Objects as Processes</long>
    </booktitle>
    <year>1998</year>
    <publisher>BRICS Notes Series</publisher>
    <volume>NS-98-5</volume>
    <month>7</month>
    <pages bgn="35" end="42" />
    <url type="pdf" href="Papers/bouncing.pdf" />
    <hal>00091895</hal>
    <abstract>
      <p>In this paper, we study a model of migrating objects based on the blue calculus, extended
        with a very simple system of localities. We show how two migration behaviors can be defined,
        namely those of bouncing and quiet objects. These migration control abstractions are defined
        separately from other aspects of the object definition and can be easily reused, thus
        providing more flexibility in the definition of migration constraints.</p>
    </abstract>
    <copyright organization="BRICS" />
    <tags>Semantics, Objects</tags>
  </inproceedings>

  <inproceedings key="blueobj">
    <authors>
      <author>&dalzilio;</author>
    </authors>
    <title>Concurrent Objects in the Blue Calculus</title>
    <booktitle>
      <short>JFLA'99</short>
      <long>10ème Journées Francophones des Langages Applicatifs</long>
    </booktitle>
    <month>2</month>
    <year>1999</year>
    <url type="pdf" href="Papers/blueobj-II.pdf" />
    <abstract>
      <p>We describe a model of concurrent objects based on the blue calculus, a typed variant of
        the asynchronous pi-calculus in which the notion of function is directly embedded. We
        propose a definition for a simple concurrent object-based calculus and show how objects can
        be translated in BC. We also present the type system for objects derived from our definition
        and we verify the expressiveness of the object calculus by giving a direct and adequate
        interpretation of Abadi and Cardelli object calculus, that preserves subtyping.</p>
    </abstract>
    <copyright organization="INRIA" />
    <tags>Semantics, Objects</tags>
  </inproceedings>

  <techreport key="rr3664">
    <authors>
      <author>&dalzilio;</author>
    </authors>
    <title>A Bisimulation for the Blue Calculus</title>
    <institution>INRIA</institution>
    <year>1999</year>
    <number>3664</number>
    <month>4</month>
    <url type="pdf" href="Papers/RR-3664.pdf" />
    <hal type="INRIA">00073008</hal>
    <abstract>
      <p>The Blue calculus is a direct extension of both the lambda and the pi calculi. In this
        report, we define an equivalence for this calculus based on barbed congruence, and we prove
        the validity of the replication laws. For example, we prove that a replicated resource,
        shared by many processes, can be safely copied and distributed.</p>
    </abstract>
    <copyright organization="INRIA" />
    <tags>Semantics, Concurrency</tags>
  </techreport>

  <phdthesis key="these">
    <authors>
      <author>&dalzilio;</author>
    </authors>
    <title>Le calcul bleu: types et objets</title>
    <school>Université de Nice - Sophia-Antipolis</school>
    <year>1999</year>
    <month>7</month>
    <url type="pdf" href="Papers/these-dalzilio.pdf" />
    <abstract>
      <p>The blue calculus, defined by Boudol, is a variant of the polyadic pi-calculus that
        directly embeds the notion of function. In this thesis, we define a version of the blue
        calculus, extended with records, and we study whether it provides a good basis for a typed
        concurrent programming language with imperative, higher-order, and object features. We
        notably study the modeling of the functional and object oriented programming idioms, and the
        addition of polymorphic typing and inheritance.</p>
      <p>The thesis is divided into four parts. The first part consists of a detailed analysis of
        the blue calculus and its expressiveness. In the second part, we define a behavioral
        equivalence based on the classical notion of barbed congruence, and a labeled bisimulation
        that is finer than this congruence. We then use up-to proof techniques to prove the validity
        of several algebraic laws like, for example, an analogous of Milner's replication theorem
        for the pi-calculus.</p>
      <p>In the third part, we study type systems for the blue calculus. Starting from a simple
        implicit type system that encompasses both Curry's type system for the lambda-calculus, and
        Milner's sorting for the pi-calculus, we successively propose three extensions of increasing
        complexity. We study the addition of subtyping, then parametric polymorphism. In this last
        case, we also study the decidability of the type inference problem. Finally, we study an
        higher-order type system with recursion and a particular form of bounded universal
        quantification. This system, that is suitable for the typing of objects, can be intuitively
        viewed as a Curry style presentation of F-sub. We prove the soundness of this system.</p>
